apiVersion: v1
kind: Template
metadata:
  name: pipeline-enable
  annotations:
    description: 'Pipeline enable an existing DeploymentConfig'
    iconClass: icon-jenkins
    tags: 'instant-app,jenkins'
objects:
  -
    apiVersion: v1
    kind: BuildConfig
    metadata:
      annotations:
        pipeline.alpha.openshift.io/uses: '[{"name": "${DEPLOYMENT_CONFIG_NAME}", "namespace": "", "kind": "DeploymentConfig"}]'
      labels:
        name: pipeline
      name: pipeline
    spec:
      strategy:
        jenkinsPipelineStrategy:
          jenkinsfile: "node('${JENKINS_SLAVE}') {\n\nstage 'Build'\nopenshiftBuild(buildConfig: '${BUILD_CONFIG_NAME}', showBuildLogs: 'true')\nstage 'Deploy to Development'\nopenshiftDeploy(deploymentConfig: '${DEPLOYMENT_CONFIG_NAME}')\nstage 'Deploy to Test'\nopenshiftTag(namespace: 'dev', sourceStream: '${BUILD_CONFIG_NAME}',  sourceTag: 'latest', destinationStream: '${BUILD_CONFIG_NAME}', destinationTag: 'promoteToTest')\nopenshiftDeploy(namespace: 'test', deploymentConfig: '${DEPLOYMENT_CONFIG_NAME}', )\nstage 'Deploy to Production'\ninput 'Deploy to Production?'\nopenshiftTag(namespace: 'dev', sourceStream: '${BUILD_CONFIG_NAME}',  sourceTag: 'latest', destinationStream: '${BUILD_CONFIG_NAME}', destinationTag: 'promoteToProd')\nopenshiftDeploy(namespace: 'prod', deploymentConfig: '${DEPLOYMENT_CONFIG_NAME}', )\nopenshiftScale(namespace: 'prod', deploymentConfig: '${DEPLOYMENT_CONFIG_NAME}',replicaCount: '3')\n}"
        type: JenkinsPipeline
      triggers:
        -
          github:
            secret: secret101
          type: GitHub
        -
          generic:
            secret: secret101
          type: Generic
parameters:
  -
    name: BUILD_CONFIG_NAME
    displayName: 'Application Build Config Name'
    description: 'The name of the OpenShift BuildConfig you want the pipeline to build.'
    required: true
  -
    name: DEPLOYMENT_CONFIG_NAME
    displayName: 'Application Deployment Config Name'
    description: 'The name of the OpenShift DeploymentConfig you want to associate the pipeline with.'
    required: true
  -
    name: JENKINS_SLAVE
    displayName: 'Jenkins target slave node'
    description: 'Jenkins slaves can be targeted to certain slave node types, such as ''maven''.'
labels:
  template: application-pipeline-template
